export default {
    message: {
        welcomeToUse: 'Welcome to use',
        qrCode: 'Promotion QR code',
        myQrCode: 'My QR code',
        qrCodeValidity: 'QR code validity period',
        myProject: 'My project',
        myGuides: 'Tour guides under my name',
        touristOrders: 'Tourist orders',
        guideReviewHis: 'Tour guide review history',
        settlementHis: 'Settlement history',
        total: 'total',
        totalAmt: 'Total amount',
        order: 'Order',
        orderNo: 'Order number',
        orderer: 'Orderer',
        orderAmt: 'Order amount',
        orderTime: 'Order time',
        completionTime: 'Completion time'
    },
    langurage: {
        chinese: 'Chinese',
        english: 'English',
        indonesia: 'Indonesia',
    },
    functions: {
        switchLanguage: 'Switch language',
        login: 'Login',
        toLogin: 'Go to login',
        forgotpw: 'Forgot password',
        selectAll: 'Select all',
        selected: 'Selected',
        reject: 'Reject',
        pass: 'Pass',
        modify: 'Modify',
        modifyInfo: 'Modify information',
        modifyStatusCompleted: 'Modification status is completed',
        cancel: 'Cancel',
        confirm: 'Confirm',
        confirmModification: 'Confirm modification',
        delete: 'Delete',
        batchDelete: 'Batch delete',
        removeGuide: 'Remove tour guide',
        add: 'Add',
        addProject: 'Add project',
        details: 'Details',
        viewDetails: 'View details',
        viewMerchantInfo: 'View merchant information',
        orderVerification: 'Order verification',
        regenerate: 'Regenerate',
        confirmEntry: 'Confirm entry',
        register: 'Register'
    },
    tips: {
        tips0: 'Prompt',
        tips1: 'Please enter the merchant name',
        tips2: 'Please enter the mobile phone number',
        tips3: 'Please enter the password',
        tips4: 'Please enter (optional)',
        tips5: 'Please enter the mobile phone verification code',
        tips6: 'Please enter the correct mobile phone number',
        tips7: 'Please confirm the password again',
        tips8: 'Please click upload',
        tips9: 'Length 8 to 16 characters, only letters and numbers',
        tips10: 'This mobile number is not registered',
        tips11: 'Don’t have an account yet?',
        tips12: 'The verification code format is incorrect',
        tips13: 'The two passwords are inconsistent',
        tips14: 'Changed the password successfully, go to log in',
        tips15: 'Visitors scan the code to place an order',
        tips16: 'You have not yet selected the list to settle',
        tips17: 'You have not logged in yet, and you cannot place an order for the time being',
        tips18: 'Unregistered mobile phone numbers will be automatically registered after verification',
        tips19: 'Please select the payment method for this visitor',
        tips20: 'Please select the merchant you want to settle in first',
        tips21: 'Please select the merchant first, and the merchant introduction will be displayed after selection',
        tips22: `Please select the merchant first, and the merchant's play items list will be displayed after selection`
    }
}