export default {
    message: {
        welcomeToUse: 'Selamat datang untuk digunakan',
        qrCode: 'Kode QR promosi',
        myQrCode: 'Kode QR saya',
        qrCodeValidity: 'Masa berlaku kode QR',
        myProject: 'Proyek saya',
        myGuides: 'Pemandu wisata atas nama saya',
        touristOrders: 'Pesanan turis',
        guideReviewHis: 'Sejarah ulasan pemandu wisata',
        settlementHis: 'Sejarah pemukiman',
        total: 'Total',
        totalAmt: 'Jumlah total',
        order: 'Memesan',
        orderNo: 'Jumlah order',
        orderer: 'Pemesan',
        orderAmt: 'Jumlah pesanan',
        orderTime: 'Waktu pemesanan',
        completionTime: 'Waktu penyelesaian'
    },
    langurage: {
        chinese: 'Cina',
        english: 'Inggris',
        indonesia: 'Bahasa Indonesia',
    },
    functions: {
        switchLanguage: 'Tukar bahasa',
        login: 'Gabung',
        toLogin: 'Pergi untuk masuk',
        forgotpw: 'Tidak ingat kata sandi',
        selectAll: 'Pilih Semua',
        selected: 'Terpilih',
        reject: 'Menolak',
        pass: 'Lulus',
        modify: 'Memodifikasi',
        modifyInfo: 'Ubah informasi',
        modifyStatusCompleted: 'Status modifikasi selesai',
        cancel: 'Membatalkan',
        confirm: 'Konfirmasikan',
        confirmModification: 'Konfirmasikan modifikasi',
        delete: 'Menghapus',
        batchDelete: 'Hapus sebagian',
        removeGuide: 'Hapus pemandu wisata',
        add: 'Menambahkan',
        addProject: 'Tambahkan proyek',
        details: 'Detail',
        viewDetails: 'Melihat rincian',
        viewMerchantInfo: 'Lihat informasi pedagang',
        orderVerification: 'Verifikasi pesanan',
        regenerate: 'Diperbarui',
        confirmEntry: 'Konfirmasikan entri',
        register: 'Mendaftar'
    },
    tips: {
        tips0: 'Mengingatkan',
        tips1: 'Silakan masukkan nama pedagang',
        tips2: 'Silakan masukkan nomor ponsel',
        tips3: 'Silakan masukkan kata sandi',
        tips4: 'Silakan masukkan (opsional)',
        tips5: 'Silakan masukkan kode verifikasi ponsel',
        tips6: 'Silakan masukkan nomor ponsel yang benar',
        tips7: 'Mohon konfirmasi kembali kata sandinya',
        tips8: 'Silakan klik unggah',
        tips9: 'Panjangnya 8 hingga 16 karakter, hanya huruf dan angka',
        tips10: 'Nomor ponsel ini tidak terdaftar',
        tips11: 'Belum punya akun?',
        tips12: 'Format kode verifikasi salah',
        tips13: 'Kedua kata sandi tersebut tidak konsisten',
        tips14: 'Berhasil mengubah kata sandi, masuk ke log masuk',
        tips15: 'Pengunjung memindai kode untuk melakukan pemesanan',
        tips16: 'Anda belum memilih daftar yang akan diselesaikan',
        tips17: 'Anda belum login, dan Anda tidak dapat melakukan pemesanan untuk saat ini',
        tips18: 'Nomor ponsel yang tidak terdaftar akan otomatis terdaftar setelah verifikasi',
        tips19: 'Silakan pilih metode pembayaran untuk pengunjung ini',
        tips20: 'Silakan pilih merchant yang ingin Anda menetapi terlebih dahulu',
        tips21: 'Silakan pilih pedagang terlebih dahulu, dan pengenalan pedagang akan ditampilkan setelah pemilihan',
        tips22: 'Silakan pilih pedagang terlebih dahulu, dan daftar item permainan pedagang akan ditampilkan setelah pemilihan'
    }
}